[project]
name = "deeplearningai-agentic-ai-m5-ugl-lab-customer-service-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=2.6.0",
    "tinydb>=4.8.2",
]
